using System.Text.Json;
using MorningstarSearch.Models.DTOs;

namespace MorningstarSearch.Tests;

public static class TestData
{
    private const string TestJson = "[\n{\n\"id\":1,\n\"first_name\":\"Antony\",\n\"last_name\":\"Fitt\",\n\"email\":\"afitt0@a8.net\",\n\"gender\":\"Male\"\n},\n{\n\"id\":2,\n\"first_name\":\"Katey\",\n\"last_name\":\"Gaines\",\n\"email\":\"kgaines1@bbb.org\",\n\"gender\":\"Female\"\n\n},\n{\n\"id\":3,\n\"first_name\":\"Ardelle\",\n\"last_name\":\"Soames\",\n\"email\":\"asoames2@google.it\",\n\"gender\":\"Female\"\n},\n{\n\"id\":4,\n\"first_name\":\"Kalila\",\n\"last_name\":\"Tennant\",\n\"email\":\"ktennant3@phpbb.com\",\n\"gender\":\"Female\"\n},\n{\n\"id\":5,\n\"first_name\":\"Veda\",\n\"last_name\":\"Emma\",\n\"email\":\"vemma4@nature.com\",\n\"gender\":\"Female\"\n},\n{\n\"id\":6,\n\"first_name\":\"Pauli\",\n\"last_name\":\"Isacke\",\n\"email\":\"pisacke5@is.gd\",\n\"gender\":\"Female\"\n},\n{\n\"id\":7,\n\"first_name\":\"Belita\",\n\"last_name\":\"Ruoff\",\n\"email\":\"bruoff6@wiley.com\",\n\"gender\":\"Female\"\n},\n{\n\"id\":8,\n\"first_name\":\"James\",\n\"last_name\":\"Kubu\",\n\"email\":\"hkubu7@craigslist.org\",\n\"gender\":\"Male\"\n},\n{\n\"id\":9,\n\"first_name\":\"Jasen\",\n\"last_name\":\"Jiroudek\",\n\"email\":\"jjiroudek8@google.it\",\n\"gender\":\"Polygender\"\n},\n{\n\"id\":10,\n\"first_name\":\"Gusty\",\n\"last_name\":\"Tuxill\",\n\"email\":\"gtuxill9@illinois.edu\",\n\"gender\":\"Female\"\n},\n{\n\"id\":11,\n\"first_name\":\"James\",\n\"last_name\":\"Pfeffer\",\n\"email\":\"bpfeffera@amazon.com\",\n\"gender\":\"Male\"\n},\n{\n\"id\":12,\n\"first_name\":\"Mignonne\",\n\"last_name\":\"Whitewood\",\n\"email\":\"mwhitewoodb@godaddy.com\",\n\"gender\":\"Female\"\n},\n\n{\n\"id\":13,\n\"first_name\":\"Moselle\",\n\"last_name\":\"Gaize\",\n\"email\":\"mgaizec@tumblr.com\",\n\"gender\":\"Female\"\n},\n{\n\"id\":14,\n\"first_name\":\"Chalmers\",\n\"last_name\":\"Longfut\",\n\"email\":\"clongfujam@wp.com\",\n\"gender\":\"Male\"\n},\n{\n\"id\":15,\n\"first_name\":\"Linnell\",\n\"last_name\":\"Jumont\",\n\"email\":\"ljumonte@storify.com\",\n\"gender\":\"Female\"\n},\n{\n\"id\":16,\n\"first_name\":\"Viole\",\n\"last_name\":\"Eaglen\",\n\"email\":\"veaglenf@nytimes.com\",\n\"gender\":\"Female\"\n},\n{\n\"id\":17,\n\"first_name\":\"Sileas\",\n\"last_name\":\"Tarr\",\n\"email\":\"starrg@telegraph.co.uk\",\n\"gender\":\"Female\"\n},\n{\n\"id\":18,\n\"first_name\":\"Katey\",\n\"last_name\":\"Soltan\",\n\"email\":\"ksoltanh@simplemachines.org\",\n\"gender\":\"Female\"\n},\n{\n\"id\":19,\n\"first_name\":\"Gar\",\n\"last_name\":\"Motion\",\n\"email\":\"gmotioni@shop-pro.jp\",\n\"gender\":\"Male\"\n},\n{\n\"id\":20,\n\"first_name\":\"Kameko\",\n\"last_name\":\"Vanes\",\n\"email\":\"kvanesj@discuz.net\",\n\"gender\":\"Female\"\n}\n\n]";

    public static List<PersonDto> TestPeople = JsonSerializer.Deserialize<List<PersonDto>>(TestJson);

}